import { prisma } from "~/server/db";

/**
 * Create new_* tables for FMS test phase. Same pattern as ParkingmgmtTableActions.
 * Uses CREATE TABLE IF NOT EXISTS and raw SQL - no migration files.
 */
export async function createNewFmsTables(): Promise<boolean> {
  const statements = [
    `CREATE TABLE IF NOT EXISTS \`new_wachtrij_transacties\` (
      \`ID\` INTEGER NOT NULL AUTO_INCREMENT,
      \`transactionDate\` TIMESTAMP(0) NULL,
      \`bikeparkID\` VARCHAR(8) NOT NULL,
      \`sectionID\` VARCHAR(13) NOT NULL,
      \`placeID\` INTEGER NULL,
      \`externalPlaceID\` VARCHAR(100) NULL,
      \`transactionID\` INTEGER NOT NULL DEFAULT 0,
      \`passID\` VARCHAR(35) NOT NULL,
      \`passtype\` VARCHAR(20) NULL,
      \`type\` VARCHAR(10) NOT NULL,
      \`typeCheck\` VARCHAR(60) NULL,
      \`price\` DECIMAL(5, 2) NULL,
      \`transaction\` TEXT NOT NULL,
      \`processed\` TINYINT(1) NOT NULL DEFAULT 0,
      \`processDate\` TIMESTAMP(0) NULL,
      \`error\` TEXT NULL,
      \`dateCreated\` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      INDEX \`new_wt_passID\`(\`passID\`),
      INDEX \`new_wt_processed\`(\`processed\`),
      INDEX \`new_wt_idx_transactionDate\`(\`transactionDate\`),
      INDEX \`new_wt_type\`(\`type\`),
      UNIQUE INDEX \`new_wt_uk_transactionDate\`(\`transactionDate\`, \`bikeparkID\`, \`sectionID\`, \`transactionID\`, \`passID\`, \`passtype\`, \`type\`),
      PRIMARY KEY (\`ID\`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS \`new_wachtrij_pasids\` (
      \`ID\` INTEGER NOT NULL AUTO_INCREMENT,
      \`transactionDate\` TIMESTAMP(0) NULL,
      \`bikeparkID\` VARCHAR(8) NOT NULL,
      \`passID\` VARCHAR(35) NOT NULL,
      \`barcode\` VARCHAR(35) NOT NULL,
      \`RFID\` VARCHAR(35) NOT NULL,
      \`RFIDBike\` VARCHAR(35) NOT NULL,
      \`biketypeID\` INTEGER NULL,
      \`bike\` TEXT NOT NULL,
      \`processed\` TINYINT(1) NOT NULL DEFAULT 0,
      \`processDate\` TIMESTAMP(0) NULL,
      \`error\` TEXT NULL,
      \`DateCreated\` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      INDEX \`new_wp_processed\`(\`processed\`),
      UNIQUE INDEX \`new_wp_uk_transactionDate\`(\`transactionDate\`, \`bikeparkID\`, \`passID\`, \`barcode\`),
      PRIMARY KEY (\`ID\`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS \`new_wachtrij_betalingen\` (
      \`ID\` INTEGER NOT NULL AUTO_INCREMENT,
      \`bikeparkID\` VARCHAR(8) NOT NULL,
      \`passID\` VARCHAR(35) NOT NULL,
      \`idtype\` INTEGER NULL,
      \`transactionDate\` DATETIME(0) NOT NULL,
      \`paymentTypeID\` INTEGER NOT NULL,
      \`amount\` DECIMAL(8, 2) NOT NULL,
      \`processed\` TINYINT(1) NOT NULL DEFAULT 0,
      \`processDate\` TIMESTAMP(0) NULL,
      \`error\` TEXT NULL,
      \`dateCreated\` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      UNIQUE INDEX \`new_wb_bikeparkID\`(\`bikeparkID\`, \`passID\`, \`transactionDate\`, \`paymentTypeID\`, \`amount\`),
      PRIMARY KEY (\`ID\`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS \`new_wachtrij_sync\` (
      \`ID\` INTEGER NOT NULL AUTO_INCREMENT,
      \`bikes\` LONGTEXT NOT NULL,
      \`bikeparkID\` VARCHAR(8) NOT NULL,
      \`sectionID\` VARCHAR(13) NOT NULL,
      \`transactionDate\` DATETIME(0) NULL,
      \`processed\` INTEGER NOT NULL DEFAULT 0,
      \`processDate\` TIMESTAMP(0) NULL,
      \`error\` TEXT NULL,
      \`dateCreated\` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      INDEX \`new_ws_bikeparkID\`(\`bikeparkID\`),
      INDEX \`new_ws_processed\`(\`processed\`),
      INDEX \`new_ws_sectionID\`(\`sectionID\`),
      INDEX \`new_ws_transactionDate\`(\`transactionDate\`),
      PRIMARY KEY (\`ID\`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS \`new_transacties\` (
      \`ID\` INTEGER NOT NULL AUTO_INCREMENT,
      \`ZipID\` VARCHAR(4) NULL,
      \`FietsenstallingID\` VARCHAR(35) NOT NULL,
      \`SectieID\` VARCHAR(13) NULL,
      \`SectieID_uit\` VARCHAR(13) NULL,
      \`PlaceID\` BIGINT NULL,
      \`ExternalPlaceID\` VARCHAR(100) NULL,
      \`PassUUID\` VARCHAR(35) NULL,
      \`PasID\` VARCHAR(35) NOT NULL,
      \`Pastype\` INTEGER NULL,
      \`BarcodeFiets_in\` VARCHAR(36) NULL,
      \`BarcodeFiets_uit\` VARCHAR(36) NULL,
      \`Date_checkin\` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      \`Date_checkout\` DATETIME(0) NULL,
      \`Stallingsduur\` INTEGER UNSIGNED NULL,
      \`Type_checkin\` VARCHAR(40) NULL,
      \`Type_checkout\` VARCHAR(40) NULL,
      \`Stallingskosten\` DECIMAL(8, 2) NULL DEFAULT 0.00,
      \`Tariefstaffels\` VARCHAR(255) NULL,
      \`BikeTypeID\` SMALLINT NOT NULL DEFAULT 1,
      \`ClientTypeID\` INTEGER NOT NULL DEFAULT 1,
      \`Reserveringsduur\` INTEGER NULL,
      \`ExploitantID\` VARCHAR(35) NULL,
      \`dateModified\` TIMESTAMP(0) NULL,
      \`dateCreated\` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      INDEX \`new_t_BarcodeFiets_in\`(\`BarcodeFiets_in\`),
      INDEX \`new_t_BikeTypeID\`(\`BikeTypeID\`),
      INDEX \`new_t_ClientTypeID\`(\`ClientTypeID\`),
      INDEX \`new_t_Date_checkin\`(\`Date_checkin\`),
      INDEX \`new_t_Date_checkout\`(\`Date_checkout\`),
      INDEX \`new_t_ExploitantID\`(\`ExploitantID\`),
      INDEX \`new_t_FietsenstallingID\`(\`FietsenstallingID\`),
      INDEX \`new_t_PasID\`(\`PasID\`),
      INDEX \`new_t_PassUUID\`(\`PassUUID\`),
      INDEX \`new_t_Pastype\`(\`Pastype\`),
      INDEX \`new_t_PlaceID\`(\`PlaceID\`),
      INDEX \`new_t_SectieID\`(\`SectieID\`),
      INDEX \`new_t_Type_checkin\`(\`Type_checkin\`),
      INDEX \`new_t_Type_checkout\`(\`Type_checkout\`),
      INDEX \`new_t_ZipID\`(\`ZipID\`),
      INDEX \`new_t_dateCreated\`(\`dateCreated\`),
      INDEX \`new_t_dateModified\`(\`dateModified\`),
      PRIMARY KEY (\`ID\`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS \`new_transacties_archief\` (
      \`ID\` INTEGER NOT NULL AUTO_INCREMENT,
      \`citycode\` VARCHAR(4) NOT NULL,
      \`locationid\` VARCHAR(8) NOT NULL,
      \`sectionid\` VARCHAR(13) NOT NULL,
      \`sectionid_out\` VARCHAR(13) NULL,
      \`placeid\` INTEGER NULL,
      \`externalplaceid\` VARCHAR(100) NULL,
      \`checkindate\` DATETIME(0) NOT NULL,
      \`checkoutdate\` DATETIME(0) NULL,
      \`checkintype\` ENUM('user', 'controle', 'system', 'sync', 'reservation') NOT NULL,
      \`checkouttype\` ENUM('user', 'controle', 'system', 'sync', 'reservation') NULL,
      \`daybeginsat\` TIME(0) NOT NULL,
      \`reservationtime\` INTEGER NULL,
      \`price\` DECIMAL(8, 2) NOT NULL DEFAULT 0.00,
      \`clienttypeid\` INTEGER NOT NULL,
      \`biketypeid\` INTEGER NOT NULL,
      \`source\` VARCHAR(35) NULL,
      \`exploitantid\` VARCHAR(35) NULL,
      \`modified\` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      \`created\` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      INDEX \`new_ta_biketypeid\`(\`biketypeid\`),
      INDEX \`new_ta_checkindate\`(\`checkindate\`),
      INDEX \`new_ta_checkoutdate\`(\`checkoutdate\`),
      INDEX \`new_ta_citycode\`(\`citycode\`),
      INDEX \`new_ta_clienttypeid\`(\`clienttypeid\`),
      INDEX \`new_ta_exploitantid\`(\`exploitantid\`),
      INDEX \`new_ta_idx_citycode_locationid\`(\`citycode\`, \`locationid\`, \`checkoutdate\`, \`sectionid\`),
      INDEX \`new_ta_locationid\`(\`locationid\`),
      INDEX \`new_ta_modified\`(\`modified\`),
      INDEX \`new_ta_placeid\`(\`placeid\`),
      INDEX \`new_ta_sectionid\`(\`sectionid\`),
      INDEX \`new_ta_source\`(\`source\`),
      PRIMARY KEY (\`ID\`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS \`new_accounts\` (
      \`ID\` VARCHAR(35) NOT NULL,
      \`Email\` VARCHAR(100) NULL,
      \`EncryptedPassword\` VARCHAR(60) NULL,
      \`Sex\` VARCHAR(10) NULL,
      \`FirstName\` VARCHAR(100) NULL,
      \`MiddleName\` VARCHAR(50) NULL,
      \`LastName\` VARCHAR(100) NULL,
      \`Address\` VARCHAR(255) NULL,
      \`Address_Nr\` VARCHAR(10) NULL,
      \`Zip\` VARCHAR(10) NULL,
      \`City\` VARCHAR(100) NULL,
      \`Phone\` VARCHAR(50) NULL,
      \`Mobile\` VARCHAR(50) NULL,
      \`Nieuwsbrief\` VARCHAR(4) NULL,
      \`Status\` VARCHAR(4) NULL DEFAULT '1',
      \`DateRegistration\` DATETIME(0) NULL,
      \`LastLogin\` DATETIME(0) NULL,
      \`DateDeleted\` DATETIME(0) NULL,
      \`WinkansInzetMehode\` ENUM('AUTO', 'HANDMATIG') NULL DEFAULT 'AUTO',
      \`saldo\` DECIMAL(10, 2) NULL DEFAULT 0.00,
      \`account_type\` ENUM('SYSTEM', 'USER', 'DELETED') NULL DEFAULT 'USER',
      \`dateLastSaldoUpdate\` TIMESTAMP(0) NULL,
      \`dateLastPrize\` DATETIME(0) NULL,
      \`nameLastPrize\` VARCHAR(255) NULL,
      UNIQUE INDEX \`new_a_Email\`(\`Email\`),
      INDEX \`new_a_Email_idx\`(\`Email\`),
      INDEX \`new_a_EncryptedPassword\`(\`EncryptedPassword\`),
      INDEX \`new_a_LastName\`(\`LastName\`),
      INDEX \`new_a_account_type\`(\`account_type\`),
      INDEX \`new_a_dateLastSaldoUpdate\`(\`dateLastSaldoUpdate\`),
      INDEX \`new_a_saldo\`(\`saldo\`),
      PRIMARY KEY (\`ID\`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS \`new_accounts_pasids\` (
      \`ID\` VARCHAR(35) NOT NULL,
      \`AccountID\` VARCHAR(35) NULL,
      \`SiteID\` VARCHAR(36) NULL,
      \`PasID\` VARCHAR(36) NOT NULL DEFAULT '',
      \`Pastype\` VARCHAR(20) NOT NULL DEFAULT 'sleutelhanger',
      \`BikeTypeID\` INTEGER NULL DEFAULT 1,
      \`Naam\` VARCHAR(255) NULL,
      \`RFID\` VARCHAR(36) NULL,
      \`RFIDBike\` VARCHAR(36) NULL,
      \`barcodeFiets\` VARCHAR(36) NULL,
      \`dateLastIdUpdate\` DATETIME(0) NULL,
      \`dateCreated\` DATETIME(0) NULL,
      \`huidigeFietsenstallingId\` VARCHAR(10) NULL,
      \`huidigeSectieId\` VARCHAR(15) NULL,
      \`huidigeStallingskosten\` DECIMAL(8, 2) NOT NULL DEFAULT 0.00,
      \`dateLastCheck\` DATETIME(0) NULL,
      \`dateModified\` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      \`dateLastSaldoUpdate\` DATETIME(0) NULL,
      \`dateLastSubscriptionUpdate\` DATETIME(0) NULL,
      \`typeLastCheckin\` VARCHAR(60) NULL,
      \`transactionID\` INTEGER NULL,
      UNIQUE INDEX \`new_ap_SiteID\`(\`SiteID\`, \`PasID\`, \`Pastype\`),
      INDEX \`new_ap_AccountID_pasID\`(\`AccountID\`, \`PasID\`),
      INDEX \`new_ap_Naam\`(\`Naam\`),
      INDEX \`new_ap_Pastype\`(\`Pastype\`),
      INDEX \`new_ap_accountID\`(\`AccountID\`),
      INDEX \`new_ap_barcodeFiets\`(\`barcodeFiets\`),
      INDEX \`new_ap_currently_parked\`(\`huidigeFietsenstallingId\`, \`huidigeSectieId\`),
      INDEX \`new_ap_dateModified\`(\`dateModified\`),
      INDEX \`new_ap_huidigeFietsenstallingId\`(\`huidigeFietsenstallingId\`),
      INDEX \`new_ap_huidigeSectieId\`(\`huidigeSectieId\`),
      INDEX \`new_ap_idx_SiteID\`(\`SiteID\`),
      INDEX \`new_ap_pasID\`(\`PasID\`),
      INDEX \`new_ap_rfid\`(\`RFID\`),
      PRIMARY KEY (\`ID\`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS \`new_financialtransactions\` (
      \`ID\` VARCHAR(35) NOT NULL,
      \`mollieTransactionID\` VARCHAR(20) NULL,
      \`amount\` DECIMAL(8, 2) NULL,
      \`btw\` DECIMAL(8, 2) NULL,
      \`btwPercentage\` DOUBLE NULL,
      \`transactionDate\` DATETIME(0) NULL,
      \`transactiekosten\` DECIMAL(8, 2) NOT NULL DEFAULT 0.00,
      \`depositDate\` DATETIME(0) NULL,
      \`paymentMethod\` VARCHAR(15) NULL,
      \`status\` VARCHAR(10) NULL,
      \`description\` VARCHAR(255) NULL,
      \`code\` VARCHAR(50) NULL,
      \`accountID\` VARCHAR(35) NULL,
      \`paidToSiteID\` VARCHAR(35) NULL,
      \`paidBySiteID\` VARCHAR(35) NULL,
      \`sourceSiteID\` VARCHAR(35) NULL,
      \`targetSiteID\` VARCHAR(35) NULL,
      \`siteID\` VARCHAR(35) NULL,
      \`bikeparkID\` VARCHAR(8) NULL,
      \`sectionID\` VARCHAR(13) NULL,
      \`placeID\` BIGINT NULL,
      \`transactionID\` INTEGER NULL,
      \`subscriptiontypeID\` INTEGER NULL,
      \`subscriptionID\` INTEGER NULL,
      \`reservationID\` INTEGER NULL,
      \`dateCreated\` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      INDEX \`new_ft_accountID_idx\`(\`accountID\`),
      INDEX \`new_ft_code\`(\`code\`),
      INDEX \`new_ft_mollieTransactionID\`(\`mollieTransactionID\`),
      INDEX \`new_ft_paidBySiteID\`(\`paidBySiteID\`),
      INDEX \`new_ft_paidToSiteID\`(\`paidToSiteID\`),
      INDEX \`new_ft_siteID\`(\`siteID\`),
      INDEX \`new_ft_sourceSiteID\`(\`sourceSiteID\`),
      INDEX \`new_ft_status\`(\`status\`),
      INDEX \`new_ft_subscriptionID\`(\`subscriptionID\`),
      INDEX \`new_ft_targetSiteID\`(\`targetSiteID\`),
      INDEX \`new_ft_transactionDate\`(\`transactionDate\`),
      INDEX \`new_ft_transactionID\`(\`transactionID\`),
      UNIQUE INDEX \`new_ft_uk_accountID\`(\`accountID\`, \`transactionDate\`, \`amount\`, \`status\`, \`code\`, \`bikeparkID\`),
      PRIMARY KEY (\`ID\`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS \`new_bezettingsdata_tmp\` (
      \`ID\` INTEGER NOT NULL AUTO_INCREMENT,
      \`timestampStartInterval\` DATETIME(0) NULL,
      \`timestamp\` DATETIME(0) NULL,
      \`interval\` INTEGER NOT NULL DEFAULT 1,
      \`source\` VARCHAR(25) NULL,
      \`bikeparkID\` VARCHAR(8) NULL,
      \`sectionID\` VARCHAR(13) NULL,
      \`brutoCapacity\` INTEGER NULL,
      \`capacity\` INTEGER NULL,
      \`bulkreserveration\` INTEGER NOT NULL DEFAULT 0,
      \`occupation\` INTEGER NULL,
      \`checkins\` INTEGER NULL,
      \`checkouts\` INTEGER NULL,
      \`open\` BIT(1) NULL,
      \`rawData\` TEXT NULL,
      \`dateModified\` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      UNIQUE INDEX \`new_bdt_timestamp_2\`(\`timestamp\`, \`interval\`, \`source\`, \`bikeparkID\`, \`sectionID\`),
      INDEX \`new_bdt_bikeparkID\`(\`bikeparkID\`),
      INDEX \`new_bdt_dateModified\`(\`dateModified\`),
      INDEX \`new_bdt_interval\`(\`interval\`),
      INDEX \`new_bdt_sectionID\`(\`sectionID\`),
      INDEX \`new_bdt_source\`(\`source\`),
      INDEX \`new_bdt_timestamp\`(\`timestamp\`),
      PRIMARY KEY (\`ID\`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
    `CREATE TABLE IF NOT EXISTS \`new_bezettingsdata\` (
      \`ID\` INTEGER NOT NULL AUTO_INCREMENT,
      \`timestampStartInterval\` DATETIME(0) NULL,
      \`timestamp\` DATETIME(0) NULL,
      \`interval\` INTEGER NOT NULL DEFAULT 1,
      \`source\` VARCHAR(25) NULL,
      \`bikeparkID\` VARCHAR(8) NULL,
      \`sectionID\` VARCHAR(13) NULL,
      \`brutoCapacity\` INTEGER NULL,
      \`capacity\` INTEGER NULL,
      \`bulkreserveration\` INTEGER NOT NULL DEFAULT 0,
      \`occupation\` INTEGER NULL,
      \`checkins\` INTEGER NULL,
      \`checkouts\` INTEGER NULL,
      \`open\` TINYINT(1) NULL,
      \`fillup\` TINYINT(1) NOT NULL DEFAULT 0,
      \`rawData\` VARCHAR(255) NULL,
      \`dateModified\` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
      \`dateCreated\` DATETIME(0) NULL,
      UNIQUE INDEX \`new_bd_timestampStartInterval\`(\`timestampStartInterval\`, \`timestamp\`, \`source\`, \`bikeparkID\`, \`sectionID\`),
      INDEX \`new_bd_bikeparkID\`(\`bikeparkID\`),
      INDEX \`new_bd_bikeparkID_source\`(\`source\`, \`bikeparkID\`),
      INDEX \`new_bd_capacity\`(\`capacity\`),
      INDEX \`new_bd_dateCreated\`(\`dateCreated\`),
      INDEX \`new_bd_dateModified\`(\`dateModified\`),
      INDEX \`new_bd_interval\`(\`interval\`),
      INDEX \`new_bd_sectionID\`(\`sectionID\`),
      INDEX \`new_bd_source\`(\`source\`),
      INDEX \`new_bd_timestamp\`(\`timestamp\`),
      PRIMARY KEY (\`ID\`)
    ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`,
  ];

  try {
    for (const stmt of statements) {
      await prisma.$executeRawUnsafe(stmt);
    }
    return true;
  } catch (e) {
    console.error("Unable to create new_* FMS tables", e);
    return false;
  }
}
