/**
 * Compares the CSV exports generated by the Next.js report services against the
 * pre-generated ColdFusion files on static.veiligstallen.nl.
 *
 * Usage:
 *   npm run compare-csv-export -- --type transacties --gemeenteID <id> --jaar 2024
 *   npm run compare-csv-export -- --type ruwedata --gemeenteID <id> --stallingsID <sid> --jaar 2024 --maand 3
 *   npm run compare-csv-export -- --type stallingsduur --gemeenteID <id> --jaar 2024
 *   npm run compare-csv-export -- --type bezetting --gemeenteID <id> --stallingsID <sid> --jaar 2024
 *
 * Sweeps:
 *   --all-stallingen        every stalling of the gemeente (transacties, ruwedata, bezetting)
 *   --all-months            every month of the year (ruwedata)
 *
 * Other options:
 *   --old-url <url>         compare against a specific URL instead of the derived one
 *   --save-dir <dir>        write both CSV files to disk for manual inspection
 *   --max-diffs <n>         number of differing cells to print per comparison (default 20)
 *
 * Requires DATABASE_URL (read from the environment or from .env / .env.local)
 * and network access to static.veiligstallen.nl.
 */

import fs from "node:fs";
import path from "node:path";

const loadEnvFile = (filename: string) => {
  const filepath = path.join(process.cwd(), filename);
  if (!fs.existsSync(filepath)) return;

  for (const rawLine of fs.readFileSync(filepath, "utf8").split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;

    const separator = line.indexOf("=");
    if (separator === -1) continue;

    const key = line.slice(0, separator).trim();
    let value = line.slice(separator + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (!(key in process.env)) {
      process.env[key] = value;
    }
  }
};

// Loaded before the Prisma client module, which reads DATABASE_URL on import.
loadEnvFile(".env.local");
loadEnvFile(".env");

const loadDeps = async () => {
  const { prisma } = await import("~/server/db");
  const { createTransactiesExport, createRuweDataExport } = await import(
    "~/backend/services/reports/transactionsExport"
  );
  const { createStallingsduurExport } = await import(
    "~/backend/services/reports/stallingsduurExport"
  );
  const { createBezettingExport } = await import("~/backend/services/reports/bezettingExport");

  return {
    prisma,
    createTransactiesExport,
    createRuweDataExport,
    createStallingsduurExport,
    createBezettingExport,
  };
};

type Deps = Awaited<ReturnType<typeof loadDeps>>;

const STATIC_BASE_URL = "https://static.veiligstallen.nl/reports";
const BOOLEAN_FLAGS = new Set(["all-stallingen", "all-months"]);

type ExportType = "transacties" | "ruwedata" | "stallingsduur" | "bezetting";

type Options = {
  type: ExportType;
  gemeenteID: string;
  stallingsID?: string;
  jaar: number;
  maand?: number;
  allStallingen: boolean;
  allMonths: boolean;
  oldUrl?: string;
  saveDir?: string;
  maxDiffs: number;
};

const parseOptions = (argv: string[]): Options => {
  const values = new Map<string, string>();
  const flags = new Set<string>();

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]!;
    if (!arg.startsWith("--")) continue;

    const key = arg.slice(2);
    const next = argv[i + 1];
    if (BOOLEAN_FLAGS.has(key) || next === undefined || next.startsWith("--")) {
      flags.add(key);
    } else {
      values.set(key, next);
      i++;
    }
  }

  const type = values.get("type") as ExportType | undefined;
  if (!type || !["transacties", "ruwedata", "stallingsduur", "bezetting"].includes(type)) {
    throw new Error(
      "--type is verplicht en moet transacties, ruwedata, stallingsduur of bezetting zijn"
    );
  }

  const gemeenteID = values.get("gemeenteID");
  if (!gemeenteID) throw new Error("--gemeenteID is verplicht");

  const jaar = Number(values.get("jaar"));
  if (!Number.isInteger(jaar)) throw new Error("--jaar is verplicht");

  const maandRaw = values.get("maand");

  return {
    type,
    gemeenteID,
    stallingsID: values.get("stallingsID"),
    jaar,
    maand: maandRaw === undefined ? undefined : Number(maandRaw),
    allStallingen: flags.has("all-stallingen"),
    allMonths: flags.has("all-months"),
    oldUrl: values.get("old-url"),
    saveDir: values.get("save-dir"),
    maxDiffs: Number(values.get("max-diffs") ?? 20),
  };
};

/** The per-stalling files switched from title based names to StallingsID in 2023. */
const perStallingNamePart = (stallingsID: string, title: string, jaar: number): string =>
  jaar < 2023 ? title.replace(/ /g, "_") : stallingsID;

const buildOldUrl = (
  options: Options,
  target: { stallingsID?: string; title?: string; maand?: number }
): string => {
  const { type, gemeenteID, jaar } = options;
  const { stallingsID, title } = target;

  switch (type) {
    case "transacties":
      if (!stallingsID) {
        return `${STATIC_BASE_URL}/${gemeenteID}/${jaar}_alle_stallingen_transacties.csv`;
      }
      return `${STATIC_BASE_URL}/${gemeenteID}/${stallingsID}/${jaar}_${perStallingNamePart(
        stallingsID,
        title ?? "",
        jaar
      )}_transacties.csv`;
    case "ruwedata": {
      const maandPadded = String(target.maand).padStart(2, "0");
      return `${STATIC_BASE_URL}/${gemeenteID}/${stallingsID!}/${jaar}_${maandPadded}_${perStallingNamePart(
        stallingsID!,
        title ?? "",
        jaar
      )}_ruwedata.csv`;
    }
    case "stallingsduur":
      return `${STATIC_BASE_URL}/${gemeenteID}/${jaar}_stallingsduur.csv`;
    case "bezetting":
      return `${STATIC_BASE_URL}/${gemeenteID}/${stallingsID!}/${jaar}_${stallingsID!}_bezetting.csv`;
  }
};

const fetchOldCsv = async (url: string): Promise<{ ok: true; text: string } | { ok: false; reason: string }> => {
  try {
    const cacheBuster = url.includes("?") ? `&${Date.now()}` : `?${Date.now()}`;
    const response = await fetch(`${url}${cacheBuster}`);
    if (!response.ok) {
      return { ok: false, reason: `HTTP ${response.status} ${response.statusText}` };
    }
    const buffer = Buffer.from(await response.arrayBuffer());
    return { ok: true, text: buffer.toString("utf8") };
  } catch (error) {
    return { ok: false, reason: error instanceof Error ? error.message : String(error) };
  }
};

const splitLines = (csv: string): string[] => {
  const lines = csv.split(/\r\n|\r|\n/);
  while (lines.length > 0 && lines[lines.length - 1] === "") {
    lines.pop();
  }
  return lines;
};

const splitCells = (line: string): string[] =>
  line.split(";").map((cell) => cell.replace(/^"/, "").replace(/"$/, ""));

const describeLineEndings = (csv: string): string => {
  const crlf = (csv.match(/\r\n/g) ?? []).length;
  const lf = (csv.match(/(?<!\r)\n/g) ?? []).length;
  const parts: string[] = [];
  if (crlf > 0) parts.push(`${crlf}x CRLF`);
  if (lf > 0) parts.push(`${lf}x LF`);
  if (parts.length === 0) parts.push("geen regeleindes");
  parts.push(csv.endsWith("\n") ? "eindigt met newline" : "eindigt zonder newline");
  return parts.join(", ");
};

type ComparisonResult = "identical" | "identical-normalized" | "different" | "unavailable";

const compareCsv = (
  label: string,
  oldCsv: string,
  newCsv: string,
  maxDiffs: number
): ComparisonResult => {
  console.log(`\n=== ${label} ===`);

  if (oldCsv === newCsv) {
    console.log("IDENTIEK (byte voor byte)");
    return "identical";
  }

  const oldLines = splitLines(oldCsv);
  const newLines = splitLines(newCsv);

  if (oldLines.join("\n") === newLines.join("\n")) {
    console.log("IDENTIEK op regeleindes na");
    console.log(`  oud: ${describeLineEndings(oldCsv)}`);
    console.log(`  nieuw: ${describeLineEndings(newCsv)}`);
    return "identical-normalized";
  }

  console.log("VERSCHILLEND");
  console.log(`  regels: oud ${oldLines.length}, nieuw ${newLines.length}`);
  console.log(`  oud: ${describeLineEndings(oldCsv)}`);
  console.log(`  nieuw: ${describeLineEndings(newCsv)}`);

  const oldHeader = oldLines.length > 0 ? splitCells(oldLines[0]!) : [];
  const newHeader = newLines.length > 0 ? splitCells(newLines[0]!) : [];

  if (oldLines[0] !== newLines[0]) {
    console.log("\n  Kopregel wijkt af:");
    console.log(`    oud:   ${oldLines[0] ?? "(leeg)"}`);
    console.log(`    nieuw: ${newLines[0] ?? "(leeg)"}`);
  }

  let printed = 0;
  const sharedLines = Math.min(oldLines.length, newLines.length);

  for (let lineIndex = 1; lineIndex < sharedLines && printed < maxDiffs; lineIndex++) {
    if (oldLines[lineIndex] === newLines[lineIndex]) continue;

    const oldCells = splitCells(oldLines[lineIndex]!);
    const newCells = splitCells(newLines[lineIndex]!);
    const cellCount = Math.max(oldCells.length, newCells.length);

    for (let cellIndex = 0; cellIndex < cellCount && printed < maxDiffs; cellIndex++) {
      const oldCell = oldCells[cellIndex];
      const newCell = newCells[cellIndex];
      if (oldCell === newCell) continue;

      const column = oldHeader[cellIndex] ?? newHeader[cellIndex] ?? `kolom ${cellIndex + 1}`;
      console.log(
        `  regel ${lineIndex + 1}, ${column}: oud=${JSON.stringify(
          oldCell ?? null
        )} nieuw=${JSON.stringify(newCell ?? null)}`
      );
      printed++;
    }
  }

  if (printed === 0 && oldLines.length !== newLines.length) {
    console.log("  Alle gedeelde regels zijn gelijk; alleen het aantal regels verschilt.");
  }

  if (oldLines.length > newLines.length) {
    console.log("\n  Alleen in het oude bestand (eerste 3):");
    for (const line of oldLines.slice(newLines.length, newLines.length + 3)) {
      console.log(`    ${line}`);
    }
  } else if (newLines.length > oldLines.length) {
    console.log("\n  Alleen in het nieuwe bestand (eerste 3):");
    for (const line of newLines.slice(oldLines.length, oldLines.length + 3)) {
      console.log(`    ${line}`);
    }
  }

  return "different";
};

const generateNewCsv = async (
  deps: Deps,
  options: Options,
  target: { stallingsID?: string; maand?: number }
): Promise<{ filename: string; csv: string }> => {
  switch (options.type) {
    case "transacties":
      return deps.createTransactiesExport({
        gemeenteID: options.gemeenteID,
        stallingsID: target.stallingsID,
        jaar: options.jaar,
      });
    case "ruwedata":
      return deps.createRuweDataExport({
        gemeenteID: options.gemeenteID,
        stallingsID: target.stallingsID,
        jaar: options.jaar,
        maand: target.maand!,
      });
    case "stallingsduur":
      return deps.createStallingsduurExport({
        gemeenteID: options.gemeenteID,
        jaar: options.jaar,
      });
    case "bezetting":
      return deps.createBezettingExport({
        gemeenteID: options.gemeenteID,
        stallingsID: target.stallingsID!,
        jaar: options.jaar,
      });
  }
};

type Stalling = { stallingsID: string; title: string };

const getStallingen = async (deps: Deps, options: Options): Promise<Stalling[]> => {
  if (!options.allStallingen) {
    if (!options.stallingsID) return [];

    const rows = await deps.prisma.$queryRaw<
      { StallingsID: string | null; Title: string | null }[]
    >`
      SELECT StallingsID, Title FROM fietsenstallingen WHERE StallingsID = ${options.stallingsID} LIMIT 1
    `;
    return [
      {
        stallingsID: options.stallingsID,
        title: rows[0]?.Title ?? "",
      },
    ];
  }

  const rows = await deps.prisma.$queryRaw<
    { StallingsID: string | null; Title: string | null }[]
  >`
    SELECT StallingsID, Title
    FROM fietsenstallingen
    WHERE SiteID = ${options.gemeenteID} AND StallingsID IS NOT NULL AND StallingsID != ''
    ORDER BY Title
  `;

  return rows.map((row) => ({ stallingsID: row.StallingsID!, title: row.Title ?? "" }));
};

const saveCsv = (saveDir: string, filename: string, suffix: string, csv: string) => {
  fs.mkdirSync(saveDir, { recursive: true });
  const target = path.join(saveDir, `${filename.replace(/\.csv$/, "")}.${suffix}.csv`);
  fs.writeFileSync(target, csv, "utf8");
  console.log(`  opgeslagen: ${target}`);
};

const main = async (deps: Deps) => {
  const options = parseOptions(process.argv.slice(2));

  type Target = { stallingsID?: string; title?: string; maand?: number };
  const targets: Target[] = [];

  if (options.type === "stallingsduur") {
    targets.push({});
  } else {
    const stallingen = await getStallingen(deps, options);

    if (options.type === "transacties" && !options.allStallingen && !options.stallingsID) {
      targets.push({});
    } else if (stallingen.length === 0) {
      throw new Error("--stallingsID of --all-stallingen is verplicht voor deze export");
    }

    for (const stalling of stallingen) {
      if (options.type === "ruwedata") {
        const maanden = options.allMonths
          ? Array.from({ length: 12 }, (_, index) => index + 1)
          : [options.maand];

        for (const maand of maanden) {
          if (!Number.isInteger(maand)) {
            throw new Error("--maand of --all-months is verplicht voor de ruwedata export");
          }
          targets.push({ ...stalling, maand: maand as number });
        }
      } else {
        targets.push(stalling);
      }
    }
  }

  const results: Record<ComparisonResult, number> = {
    identical: 0,
    "identical-normalized": 0,
    different: 0,
    unavailable: 0,
  };

  for (const target of targets) {
    const { filename, csv: newCsv } = await generateNewCsv(deps, options, target);
    const url = options.oldUrl ?? buildOldUrl(options, target);
    const label = `${filename}  <-  ${url}`;

    const old = await fetchOldCsv(url);
    if (!old.ok) {
      console.log(`\n=== ${label} ===`);
      console.log(`OUD BESTAND NIET BESCHIKBAAR: ${old.reason}`);
      console.log(`  nieuw bestand: ${splitLines(newCsv).length} regels`);
      results.unavailable++;
      if (options.saveDir) saveCsv(options.saveDir, filename, "new", newCsv);
      continue;
    }

    const result = compareCsv(label, old.text, newCsv, options.maxDiffs);
    results[result]++;

    if (options.saveDir) {
      saveCsv(options.saveDir, filename, "old", old.text);
      saveCsv(options.saveDir, filename, "new", newCsv);
    }
  }

  console.log("\n--- Samenvatting ---");
  console.log(`identiek:                 ${results.identical}`);
  console.log(`identiek na normalisatie: ${results["identical-normalized"]}`);
  console.log(`verschillend:             ${results.different}`);
  console.log(`oud bestand ontbreekt:    ${results.unavailable}`);

  if (results.different > 0) {
    process.exitCode = 1;
  }
};

const run = async () => {
  const deps = await loadDeps();
  try {
    await main(deps);
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  } finally {
    await deps.prisma.$disconnect().catch(() => undefined);
  }
};

void run();
