/**
 * Generated by: npx tsx scripts/extract-stallings.ts [--config path/to/config.json]
 * IDs are replaced: source StallingsID (e.g. 3500_005) -> target (e.g. 9933_001)
 * Config: {"stallingsCount":7,"stallings":[{"stallingID":"E2C3170A-EE9B-B3B4-D17D7CBE42AF7515","newstallingname":"9933_001","name":"API Betaalde Stalling"},{"stallingID":"A32A713E-1960-4405-892A074407693784","newstallingname":"9933_002","name":"API Buurtstalling"},{"stallingID":"81628706-9F3D-4EB2-91F0D33CCBF483A3","newstallingname":"9933_003","name":"API Fietskluizen"},{"stallingID":"E2C31F68-B67A-467F-6D12DF5DC9F926B6","newstallingname":"9933_004","name":"API Geautomatiseerde Stalling"},{"stallingID":"B77B5162-5ECA-4728-B5BC27D2E45816F0","newstallingname":"9933_005","name":"API Onbewaakte Stalling"},{"stallingID":"61D5F5A3-B0B4-4085-9A1A648B7D5EB8A9","newstallingname":"9933_006","name":"API Fietstrommel"},{"stallingID":"27006D80-B4BF-E371-8C622431B303ECCE","newstallingname":"9933_007","name":"API Toezicht"}]}
 */

export const STALLING_DATA_BY_TARGET: Record<string, {
  fietsenstallingen: Record<string, unknown>;
  sectiesTree: unknown[];
  tarievenTree: unknown;
  abonnementsvormenTree: unknown[];
  services: unknown[];
  winkansen: unknown[];
  uitzonderingenopeningstijden: unknown[];
}> = {
  "9933_001": {
    "fietsenstallingen": {
      "StallingsID": "9933_001",
      "Title": "9933_001 - API Betaalde Stalling",
      "StallingsIDExtern": null,
      "Description": null,
      "Image": "",
      "Location": "Godebaldkwartier 74 ",
      "Postcode": "3511 DZ",
      "Plaats": "Utrecht",
      "Capacity": 833,
      "Openingstijden": "<p><em>Donderdag vanaf 07.00 uur permanent open t/m maandag 01.00 uur.</em></p>\r\n\r\n<p><a href=\"https://u-stal.nl/images/Afbeeldingen/PDF-documenten/20210720_Algemene-Voorwaarden-fietsenstallingen_DvdS2482021.pdf\" target=\"_blank\">Klik hier </a>voor de Algemene voorwaarden gebruik openbare fietsenstallingen gemeente Utrecht.</p>\r\n",
      "Status": "1",
      "Ip": null,
      "Coordinaten": "52.092655,5.114168",
      "Type": "bewaakt",
      "Verwijssysteem": false,
      "VerwijssysteemOverzichten": true,
      "FMS": true,
      "Open_ma": "1970-01-01T07:00:00.000Z",
      "Dicht_ma": "1970-01-01T01:00:00.000Z",
      "Open_di": "1970-01-01T07:00:00.000Z",
      "Dicht_di": "1970-01-01T01:00:00.000Z",
      "Open_wo": "1970-01-01T07:00:00.000Z",
      "Dicht_wo": "1970-01-01T01:00:00.000Z",
      "Open_do": "1970-01-01T07:00:00.000Z",
      "Dicht_do": "1970-01-01T00:00:00.000Z",
      "Open_vr": "1970-01-01T00:00:00.000Z",
      "Dicht_vr": "1970-01-01T23:59:00.000Z",
      "Open_za": "1970-01-01T00:00:00.000Z",
      "Dicht_za": "1970-01-01T23:59:00.000Z",
      "Open_zo": "1970-01-01T00:00:00.000Z",
      "Dicht_zo": "1970-01-01T23:59:00.000Z",
      "OmschrijvingTarieven": null,
      "IsStationsstalling": false,
      "IsPopup": false,
      "NotaVerwijssysteem": null,
      "Tariefcode": 5,
      "Toegangscontrole": 0,
      "Beheerder": null,
      "BeheerderContact": "http://www.u-stal.nl/",
      "HelpdeskHandmatigIngesteld": false,
      "Url": null,
      "ExtraServices": null,
      "dia": null,
      "BerekentStallingskosten": true,
      "AantalReserveerbareKluizen": 0,
      "MaxStallingsduur": 0,
      "HeeftExterneBezettingsdata": false,
      "hasUniSectionPrices": false,
      "hasUniBikeTypePrices": false,
      "shadowBikeparkID": null,
      "BronBezettingsdata": "FMS",
      "reservationCostPerDay": "0",
      "wachtlijst_Id": null,
      "thirdPartyReservationsUrl": null
    },
    "sectiesTree": [
      {
        "externalId": "9933_001_1",
        "titel": "Deze stalling",
        "omschrijving": "",
        "capaciteit": 833,
        "CapaciteitBromfiets": null,
        "kleur": "00FF00",
        "isKluis": false,
        "reserveringskostenPerDag": null,
        "urlwebservice": "",
        "Reservable": false,
        "NotaVerwijssysteem": "",
        "Bezetting": 325,
        "isactief": true,
        "qualificatie": "NONE",
        "sectieFietstypes": [
          {
            "BikeTypeID": 1
          },
          {
            "BikeTypeID": 2
          },
          {
            "BikeTypeID": 3
          },
          {
            "BikeTypeID": 4
          },
          {
            "BikeTypeID": 5
          },
          {
            "BikeTypeID": 6
          },
          {
            "BikeTypeID": 7
          },
          {
            "BikeTypeID": 8
          },
          {
            "BikeTypeID": 9
          },
          {
            "BikeTypeID": 10
          },
          {
            "BikeTypeID": 11
          },
          {
            "BikeTypeID": 12
          },
          {
            "BikeTypeID": 13
          }
        ],
        "kostenperioden": [
          {
            "index": 1,
            "tijdsspanne": "",
            "kosten": ""
          },
          {
            "index": 1,
            "tijdsspanne": "",
            "kosten": ""
          },
          {
            "index": 1,
            "tijdsspanne": "",
            "kosten": ""
          }
        ]
      }
    ],
    "tarievenTree": {
      "stalling": [
        {
          "index": 1,
          "tijdsspanne": 24,
          "kosten": "0",
          "truncatedStallingsID": "9933_001",
          "truncatedSectieID": null
        },
        {
          "index": 2,
          "tijdsspanne": 24,
          "kosten": "0.5",
          "truncatedStallingsID": "9933_001",
          "truncatedSectieID": null
        }
      ],
      "sections": [
        {
          "externalId": "9933_001_1",
          "tariefregels": [],
          "bikeTypes": []
        }
      ]
    },
    "abonnementsvormenTree": [
      {
        "SubscriptiontypeID": 7,
        "BikeTypeIDs": [
          1,
          3,
          4,
          6,
          7,
          8,
          1,
          3,
          4,
          6,
          7,
          8,
          1,
          3,
          4,
          6,
          7,
          8,
          1,
          3,
          4,
          6,
          7,
          8,
          1,
          3,
          4,
          6,
          7,
          8,
          1,
          3,
          4,
          6,
          7,
          8
        ]
      }
    ],
    "services": [
      {
        "ServiceID": "buggy"
      },
      {
        "ServiceID": "fietspomp"
      },
      {
        "ServiceID": "oplaadpunt"
      },
      {
        "ServiceID": "toilet"
      }
    ],
    "winkansen": [],
    "uitzonderingenopeningstijden": [
      {
        "openingDateTime": "2016-03-27T00:00:00.000Z",
        "closingDateTime": "2016-03-27T23:59:00.000Z"
      },
      {
        "openingDateTime": "2016-03-28T11:30:00.000Z",
        "closingDateTime": "2016-03-29T01:00:00.000Z"
      },
      {
        "openingDateTime": "2016-04-26T07:00:00.000Z",
        "closingDateTime": "2016-04-26T07:00:00.000Z"
      },
      {
        "openingDateTime": "2016-04-27T07:00:00.000Z",
        "closingDateTime": "2016-04-28T01:00:00.000Z"
      },
      {
        "openingDateTime": "2016-05-05T11:30:00.000Z",
        "closingDateTime": "2016-05-06T01:00:00.000Z"
      },
      {
        "openingDateTime": "2016-05-16T11:30:00.000Z",
        "closingDateTime": "2016-05-17T01:00:00.000Z"
      },
      {
        "openingDateTime": "2016-12-26T11:30:00.000Z",
        "closingDateTime": "2016-12-27T01:00:00.000Z"
      },
      {
        "openingDateTime": "2017-12-25T11:00:00.000Z",
        "closingDateTime": "2017-12-26T01:00:00.000Z"
      },
      {
        "openingDateTime": "2017-12-26T11:30:00.000Z",
        "closingDateTime": "2017-12-27T01:00:00.000Z"
      },
      {
        "openingDateTime": "2017-12-31T00:00:00.000Z",
        "closingDateTime": "2017-12-31T22:00:00.000Z"
      },
      {
        "openingDateTime": "2018-01-01T11:30:00.000Z",
        "closingDateTime": "2018-01-02T01:00:00.000Z"
      },
      {
        "openingDateTime": "2018-04-02T11:30:00.000Z",
        "closingDateTime": "2018-04-03T01:00:00.000Z"
      },
      {
        "openingDateTime": "2018-05-20T11:30:00.000Z",
        "closingDateTime": "2018-05-21T01:00:00.000Z"
      },
      {
        "openingDateTime": "2018-12-25T11:30:00.000Z",
        "closingDateTime": "2018-12-26T01:00:00.000Z"
      },
      {
        "openingDateTime": "2018-12-26T11:30:00.000Z",
        "closingDateTime": "2018-12-27T01:00:00.000Z"
      },
      {
        "openingDateTime": "2018-12-31T07:00:00.000Z",
        "closingDateTime": "2018-12-31T22:00:00.000Z"
      },
      {
        "openingDateTime": "2019-01-01T11:30:00.000Z",
        "closingDateTime": "2019-01-02T01:00:00.000Z"
      },
      {
        "openingDateTime": "2019-12-31T07:00:00.000Z",
        "closingDateTime": "2019-12-31T22:00:00.000Z"
      },
      {
        "openingDateTime": "2020-01-01T11:30:00.000Z",
        "closingDateTime": "2020-01-02T01:00:00.000Z"
      },
      {
        "openingDateTime": "2020-06-01T07:00:00.000Z",
        "closingDateTime": "2020-06-02T00:00:00.000Z"
      },
      {
        "openingDateTime": "2020-12-31T07:00:00.000Z",
        "closingDateTime": "2020-12-31T22:00:00.000Z"
      },
      {
        "openingDateTime": "2021-01-01T11:30:00.000Z",
        "closingDateTime": "2021-01-02T00:00:00.000Z"
      },
      {
        "openingDateTime": "2021-05-13T07:00:00.000Z",
        "closingDateTime": "2021-05-14T01:00:00.000Z"
      },
      {
        "openingDateTime": "2021-05-24T07:00:00.000Z",
        "closingDateTime": "2021-05-25T00:00:00.000Z"
      },
      {
        "openingDateTime": "2022-01-01T07:00:00.000Z",
        "closingDateTime": "2022-01-02T00:00:00.000Z"
      },
      {
        "openingDateTime": "2021-12-31T00:00:00.000Z",
        "closingDateTime": "2021-12-31T22:00:00.000Z"
      },
      {
        "openingDateTime": "2022-04-26T00:00:00.000Z",
        "closingDateTime": "2022-04-26T23:59:00.000Z"
      },
      {
        "openingDateTime": "2022-04-27T00:00:00.000Z",
        "closingDateTime": "2022-04-27T23:59:00.000Z"
      },
      {
        "openingDateTime": "2023-12-26T07:00:00.000Z",
        "closingDateTime": "2023-12-27T05:00:00.000Z"
      }
    ]
  },
  "9933_002": {
    "fietsenstallingen": {
      "StallingsID": "9933_002",
      "Title": "9933_002 - API Buurtstalling",
      "StallingsIDExtern": null,
      "Description": null,
      "Image": null,
      "Location": "Mariaplaats 2",
      "Postcode": null,
      "Plaats": "Utrecht",
      "Capacity": 30,
      "Openingstijden": null,
      "Status": "1",
      "Ip": null,
      "Coordinaten": "52.089877, 5.118421",
      "Type": "buurtstalling",
      "Verwijssysteem": false,
      "VerwijssysteemOverzichten": false,
      "FMS": true,
      "Open_ma": "1970-01-01T00:00:00.000Z",
      "Dicht_ma": "1970-01-01T23:59:00.000Z",
      "Open_di": "1970-01-01T00:00:00.000Z",
      "Dicht_di": "1970-01-01T23:59:00.000Z",
      "Open_wo": "1970-01-01T00:00:00.000Z",
      "Dicht_wo": "1970-01-01T23:59:00.000Z",
      "Open_do": "1970-01-01T00:00:00.000Z",
      "Dicht_do": "1970-01-01T23:59:00.000Z",
      "Open_vr": "1970-01-01T00:00:00.000Z",
      "Dicht_vr": "1970-01-01T23:59:00.000Z",
      "Open_za": "1970-01-01T00:00:00.000Z",
      "Dicht_za": "1970-01-01T23:59:00.000Z",
      "Open_zo": "1970-01-01T00:00:00.000Z",
      "Dicht_zo": "1970-01-01T23:59:00.000Z",
      "OmschrijvingTarieven": null,
      "IsStationsstalling": false,
      "IsPopup": false,
      "NotaVerwijssysteem": null,
      "Tariefcode": 1,
      "Toegangscontrole": 1,
      "Beheerder": null,
      "BeheerderContact": "http://www.u-stal.nl/locaties-fietsenstallingen/buurtstallingen",
      "HelpdeskHandmatigIngesteld": false,
      "Url": null,
      "ExtraServices": null,
      "dia": null,
      "BerekentStallingskosten": true,
      "AantalReserveerbareKluizen": 0,
      "MaxStallingsduur": 0,
      "HeeftExterneBezettingsdata": false,
      "hasUniSectionPrices": false,
      "hasUniBikeTypePrices": false,
      "shadowBikeparkID": null,
      "BronBezettingsdata": "FMS",
      "reservationCostPerDay": "0",
      "wachtlijst_Id": 66,
      "thirdPartyReservationsUrl": null
    },
    "sectiesTree": [
      {
        "externalId": "9933_002_1",
        "titel": "Onderrek fiets",
        "omschrijving": "",
        "capaciteit": 30,
        "CapaciteitBromfiets": null,
        "kleur": "00FF00",
        "isKluis": false,
        "reserveringskostenPerDag": null,
        "urlwebservice": "",
        "Reservable": false,
        "NotaVerwijssysteem": null,
        "Bezetting": 0,
        "isactief": true,
        "qualificatie": "NONE",
        "sectieFietstypes": [
          {
            "BikeTypeID": 1
          },
          {
            "BikeTypeID": 2
          },
          {
            "BikeTypeID": 3
          },
          {
            "BikeTypeID": 4
          },
          {
            "BikeTypeID": 5
          },
          {
            "BikeTypeID": 6
          },
          {
            "BikeTypeID": 7
          },
          {
            "BikeTypeID": 8
          }
        ],
        "kostenperioden": []
      }
    ],
    "tarievenTree": {
      "stalling": [],
      "sections": [
        {
          "externalId": "9933_002_1",
          "tariefregels": [],
          "bikeTypes": []
        }
      ]
    },
    "abonnementsvormenTree": [
      {
        "SubscriptiontypeID": 157,
        "BikeTypeIDs": [
          1,
          4,
          1,
          4,
          1,
          4,
          1,
          4,
          1,
          4,
          1,
          4
        ]
      }
    ],
    "services": [],
    "winkansen": [],
    "uitzonderingenopeningstijden": []
  },
  "9933_003": {
    "fietsenstallingen": {
      "StallingsID": "9933_003",
      "Title": "9933_003 - API Fietskluizen",
      "StallingsIDExtern": null,
      "Description": "Stal veilig jouw (e-)fiets in een van onze fietskluizen. Meer zekerheid met je eigen kluis? Neem dan een maand- of jaarabonnement.",
      "Image": "",
      "Location": "N214",
      "Postcode": null,
      "Plaats": "Bleskensgraaf",
      "Capacity": 4,
      "Openingstijden": null,
      "Status": "1",
      "Ip": null,
      "Coordinaten": "51.857033,4.789375",
      "Type": "fietskluizen",
      "Verwijssysteem": false,
      "VerwijssysteemOverzichten": false,
      "FMS": true,
      "Open_ma": null,
      "Dicht_ma": null,
      "Open_di": null,
      "Dicht_di": null,
      "Open_wo": null,
      "Dicht_wo": null,
      "Open_do": null,
      "Dicht_do": null,
      "Open_vr": null,
      "Dicht_vr": null,
      "Open_za": null,
      "Dicht_za": null,
      "Open_zo": null,
      "Dicht_zo": null,
      "OmschrijvingTarieven": null,
      "IsStationsstalling": false,
      "IsPopup": false,
      "NotaVerwijssysteem": null,
      "Tariefcode": 1,
      "Toegangscontrole": null,
      "Beheerder": null,
      "BeheerderContact": "klantenservicedmg@qbuzz.nl",
      "HelpdeskHandmatigIngesteld": false,
      "Url": null,
      "ExtraServices": null,
      "dia": null,
      "BerekentStallingskosten": false,
      "AantalReserveerbareKluizen": 2,
      "MaxStallingsduur": 0,
      "HeeftExterneBezettingsdata": false,
      "hasUniSectionPrices": true,
      "hasUniBikeTypePrices": true,
      "shadowBikeparkID": null,
      "BronBezettingsdata": "FMS",
      "reservationCostPerDay": null,
      "wachtlijst_Id": null,
      "thirdPartyReservationsUrl": null
    },
    "sectiesTree": [
      {
        "externalId": "9933_003_1",
        "titel": "Kluizen",
        "omschrijving": "",
        "capaciteit": 4,
        "CapaciteitBromfiets": null,
        "kleur": "00FF00",
        "isKluis": false,
        "reserveringskostenPerDag": null,
        "urlwebservice": null,
        "Reservable": false,
        "NotaVerwijssysteem": null,
        "Bezetting": 0,
        "isactief": true,
        "qualificatie": null,
        "sectieFietstypes": [
          {
            "BikeTypeID": 1
          },
          {
            "BikeTypeID": 2
          },
          {
            "BikeTypeID": 3
          },
          {
            "BikeTypeID": 4
          },
          {
            "BikeTypeID": 5
          },
          {
            "BikeTypeID": 6
          }
        ],
        "kostenperioden": []
      }
    ],
    "tarievenTree": {
      "stalling": [
        {
          "index": 1,
          "tijdsspanne": 8,
          "kosten": "1",
          "truncatedStallingsID": null,
          "truncatedSectieID": null
        }
      ],
      "sections": [
        {
          "externalId": "9933_003_1",
          "tariefregels": [],
          "bikeTypes": []
        }
      ]
    },
    "abonnementsvormenTree": [
      {
        "SubscriptiontypeID": 162,
        "BikeTypeIDs": []
      },
      {
        "SubscriptiontypeID": 163,
        "BikeTypeIDs": []
      }
    ],
    "services": [],
    "winkansen": [],
    "uitzonderingenopeningstijden": []
  },
  "9933_004": {
    "fietsenstallingen": {
      "StallingsID": "9933_004",
      "Title": "9933_004 - API Geautomatiseerde Stalling",
      "StallingsIDExtern": null,
      "Description": null,
      "Image": null,
      "Location": "Orlyplein 109 ",
      "Postcode": "1043 DT",
      "Plaats": "Amsterdam",
      "Capacity": 0,
      "Openingstijden": "Deze spitsstalling is geopend van een kwartier voor de eerste tot en met een kwartier na de laatste trein. Tijdens de spits is deze stalling bemenst: \r\n’s ochtends van 07:00u t/m 10:00u \r\n’s avonds van 16:00u t/m 19:00u",
      "Status": "1",
      "Ip": null,
      "Coordinaten": "52.389030,4.837070",
      "Type": "geautomatiseerd",
      "Verwijssysteem": false,
      "VerwijssysteemOverzichten": false,
      "FMS": false,
      "Open_ma": "1970-01-01T05:00:00.000Z",
      "Dicht_ma": "1970-01-01T02:15:00.000Z",
      "Open_di": "1970-01-01T05:00:00.000Z",
      "Dicht_di": "1970-01-01T02:15:00.000Z",
      "Open_wo": "1970-01-01T05:00:00.000Z",
      "Dicht_wo": "1970-01-01T02:45:00.000Z",
      "Open_do": "1970-01-01T05:00:00.000Z",
      "Dicht_do": "1970-01-01T02:15:00.000Z",
      "Open_vr": "1970-01-01T05:00:00.000Z",
      "Dicht_vr": "1970-01-01T02:15:00.000Z",
      "Open_za": "1970-01-01T05:00:00.000Z",
      "Dicht_za": "1970-01-01T02:00:00.000Z",
      "Open_zo": "1970-01-01T05:15:00.000Z",
      "Dicht_zo": "1970-01-01T02:00:00.000Z",
      "OmschrijvingTarieven": null,
      "IsStationsstalling": true,
      "IsPopup": false,
      "NotaVerwijssysteem": null,
      "Tariefcode": 1,
      "Toegangscontrole": 2,
      "Beheerder": "NS Fiets",
      "BeheerderContact": "www.nsfiets.nl",
      "HelpdeskHandmatigIngesteld": true,
      "Url": null,
      "ExtraServices": null,
      "dia": null,
      "BerekentStallingskosten": true,
      "AantalReserveerbareKluizen": 0,
      "MaxStallingsduur": 0,
      "HeeftExterneBezettingsdata": false,
      "hasUniSectionPrices": true,
      "hasUniBikeTypePrices": false,
      "shadowBikeparkID": null,
      "BronBezettingsdata": "FMS",
      "reservationCostPerDay": null,
      "wachtlijst_Id": null,
      "thirdPartyReservationsUrl": null
    },
    "sectiesTree": [
      {
        "externalId": "9933_004_1",
        "titel": "Sectie 1",
        "omschrijving": "",
        "capaciteit": 0,
        "CapaciteitBromfiets": null,
        "kleur": "00FF00",
        "isKluis": false,
        "reserveringskostenPerDag": null,
        "urlwebservice": "",
        "Reservable": false,
        "NotaVerwijssysteem": null,
        "Bezetting": 0,
        "isactief": true,
        "qualificatie": "NONE",
        "sectieFietstypes": [],
        "kostenperioden": [
          {
            "index": 1,
            "tijdsspanne": "",
            "kosten": ""
          },
          {
            "index": 1,
            "tijdsspanne": "",
            "kosten": ""
          },
          {
            "index": 1,
            "tijdsspanne": "",
            "kosten": ""
          }
        ]
      }
    ],
    "tarievenTree": {
      "stalling": [],
      "sections": [
        {
          "externalId": "9933_004_1",
          "tariefregels": [],
          "bikeTypes": []
        }
      ]
    },
    "abonnementsvormenTree": [],
    "services": [],
    "winkansen": [],
    "uitzonderingenopeningstijden": []
  },
  "9933_005": {
    "fietsenstallingen": {
      "StallingsID": "9933_005",
      "Title": "9933_005 - API Onbewaakte Stalling",
      "StallingsIDExtern": null,
      "Description": "dubbele rekken",
      "Image": "",
      "Location": "Moreelsepark",
      "Postcode": null,
      "Plaats": "Utrecht",
      "Capacity": 0,
      "Openingstijden": null,
      "Status": "0",
      "Ip": null,
      "Coordinaten": "52.08906989416835,5.113946346203647",
      "Type": "onbewaakt",
      "Verwijssysteem": false,
      "VerwijssysteemOverzichten": false,
      "FMS": false,
      "Open_ma": "1970-01-01T00:00:00.000Z",
      "Dicht_ma": "1970-01-01T23:59:00.000Z",
      "Open_di": "1970-01-01T00:00:00.000Z",
      "Dicht_di": "1970-01-01T23:59:00.000Z",
      "Open_wo": "1970-01-01T00:00:00.000Z",
      "Dicht_wo": "1970-01-01T23:59:00.000Z",
      "Open_do": "1970-01-01T00:00:00.000Z",
      "Dicht_do": "1970-01-01T23:59:00.000Z",
      "Open_vr": "1970-01-01T00:00:00.000Z",
      "Dicht_vr": "1970-01-01T23:59:00.000Z",
      "Open_za": "1970-01-01T00:00:00.000Z",
      "Dicht_za": "1970-01-01T23:59:00.000Z",
      "Open_zo": "1970-01-01T00:00:00.000Z",
      "Dicht_zo": "1970-01-01T23:59:00.000Z",
      "OmschrijvingTarieven": null,
      "IsStationsstalling": true,
      "IsPopup": false,
      "NotaVerwijssysteem": null,
      "Tariefcode": 2,
      "Toegangscontrole": 1,
      "Beheerder": "Gemeente Utrecht",
      "BeheerderContact": null,
      "HelpdeskHandmatigIngesteld": true,
      "Url": null,
      "ExtraServices": null,
      "dia": null,
      "BerekentStallingskosten": true,
      "AantalReserveerbareKluizen": 0,
      "MaxStallingsduur": 0,
      "HeeftExterneBezettingsdata": false,
      "hasUniSectionPrices": false,
      "hasUniBikeTypePrices": false,
      "shadowBikeparkID": null,
      "BronBezettingsdata": "FMS",
      "reservationCostPerDay": null,
      "wachtlijst_Id": null,
      "thirdPartyReservationsUrl": null
    },
    "sectiesTree": [],
    "tarievenTree": {
      "stalling": [],
      "sections": []
    },
    "abonnementsvormenTree": [],
    "services": [],
    "winkansen": [],
    "uitzonderingenopeningstijden": []
  },
  "9933_006": {
    "fietsenstallingen": {
      "StallingsID": "9933_006",
      "Title": "9933_006 - API Fietstrommel",
      "StallingsIDExtern": null,
      "Description": null,
      "Image": null,
      "Location": "Merwedekade 222",
      "Postcode": null,
      "Plaats": "Utrecht",
      "Capacity": 4,
      "Openingstijden": null,
      "Status": "1",
      "Ip": null,
      "Coordinaten": "52.070040, 5.112035",
      "Type": "fietstrommel",
      "Verwijssysteem": false,
      "VerwijssysteemOverzichten": false,
      "FMS": true,
      "Open_ma": "1970-01-01T00:00:00.000Z",
      "Dicht_ma": "1970-01-01T23:59:00.000Z",
      "Open_di": "1970-01-01T00:00:00.000Z",
      "Dicht_di": "1970-01-01T23:59:00.000Z",
      "Open_wo": "1970-01-01T00:00:00.000Z",
      "Dicht_wo": "1970-01-01T23:59:00.000Z",
      "Open_do": "1970-01-01T00:00:00.000Z",
      "Dicht_do": "1970-01-01T23:59:00.000Z",
      "Open_vr": "1970-01-01T00:00:00.000Z",
      "Dicht_vr": "1970-01-01T23:59:00.000Z",
      "Open_za": "1970-01-01T00:00:00.000Z",
      "Dicht_za": "1970-01-01T23:59:00.000Z",
      "Open_zo": "1970-01-01T00:00:00.000Z",
      "Dicht_zo": "1970-01-01T23:59:00.000Z",
      "OmschrijvingTarieven": null,
      "IsStationsstalling": false,
      "IsPopup": false,
      "NotaVerwijssysteem": null,
      "Tariefcode": 1,
      "Toegangscontrole": 0,
      "Beheerder": null,
      "BeheerderContact": "http://www.u-stal.nl/locaties-fietsenstallingen/fietstrommels",
      "HelpdeskHandmatigIngesteld": false,
      "Url": null,
      "ExtraServices": null,
      "dia": null,
      "BerekentStallingskosten": true,
      "AantalReserveerbareKluizen": 0,
      "MaxStallingsduur": 0,
      "HeeftExterneBezettingsdata": false,
      "hasUniSectionPrices": false,
      "hasUniBikeTypePrices": false,
      "shadowBikeparkID": null,
      "BronBezettingsdata": "FMS",
      "reservationCostPerDay": "0",
      "wachtlijst_Id": 105,
      "thirdPartyReservationsUrl": null
    },
    "sectiesTree": [
      {
        "externalId": "9933_006_1",
        "titel": "Onderrek fiets",
        "omschrijving": "",
        "capaciteit": 4,
        "CapaciteitBromfiets": null,
        "kleur": "00FF00",
        "isKluis": false,
        "reserveringskostenPerDag": null,
        "urlwebservice": "",
        "Reservable": false,
        "NotaVerwijssysteem": null,
        "Bezetting": 0,
        "isactief": true,
        "qualificatie": "NONE",
        "sectieFietstypes": [
          {
            "BikeTypeID": 1
          },
          {
            "BikeTypeID": 2
          },
          {
            "BikeTypeID": 3
          },
          {
            "BikeTypeID": 4
          },
          {
            "BikeTypeID": 5
          },
          {
            "BikeTypeID": 6
          },
          {
            "BikeTypeID": 7
          },
          {
            "BikeTypeID": 8
          }
        ],
        "kostenperioden": []
      }
    ],
    "tarievenTree": {
      "stalling": [],
      "sections": [
        {
          "externalId": "9933_006_1",
          "tariefregels": [],
          "bikeTypes": []
        }
      ]
    },
    "abonnementsvormenTree": [
      {
        "SubscriptiontypeID": 151,
        "BikeTypeIDs": [
          1,
          1,
          1,
          1,
          1,
          1
        ]
      }
    ],
    "services": [],
    "winkansen": [],
    "uitzonderingenopeningstijden": []
  },
  "9933_007": {
    "fietsenstallingen": {
      "StallingsID": "9933_007",
      "Title": "9933_007 - API Toezicht",
      "StallingsIDExtern": null,
      "Description": "Hier wordt uw fiets gratis bewaakt.",
      "Image": "P1100403.JPG",
      "Location": "Museumpassage bij Caterplein",
      "Postcode": "7311 BR",
      "Plaats": "Apeldoorn",
      "Capacity": 860,
      "Openingstijden": null,
      "Status": "1",
      "Ip": "188.203.244.17",
      "Coordinaten": "52.215952,5.957605",
      "Type": "toezicht",
      "Verwijssysteem": true,
      "VerwijssysteemOverzichten": true,
      "FMS": true,
      "Open_ma": "1970-01-01T07:00:00.000Z",
      "Dicht_ma": "1970-01-01T01:00:00.000Z",
      "Open_di": "1970-01-01T07:00:00.000Z",
      "Dicht_di": "1970-01-01T01:00:00.000Z",
      "Open_wo": "1970-01-01T07:00:00.000Z",
      "Dicht_wo": "1970-01-01T01:00:00.000Z",
      "Open_do": "1970-01-01T07:00:00.000Z",
      "Dicht_do": "1970-01-01T02:00:00.000Z",
      "Open_vr": "1970-01-01T07:00:00.000Z",
      "Dicht_vr": "1970-01-01T04:30:00.000Z",
      "Open_za": "1970-01-01T11:30:00.000Z",
      "Dicht_za": "1970-01-01T04:30:00.000Z",
      "Open_zo": "1970-01-01T11:30:00.000Z",
      "Dicht_zo": "1970-01-01T01:00:00.000Z",
      "OmschrijvingTarieven": null,
      "IsStationsstalling": false,
      "IsPopup": false,
      "NotaVerwijssysteem": null,
      "Tariefcode": 2,
      "Toegangscontrole": 0,
      "Beheerder": null,
      "BeheerderContact": null,
      "HelpdeskHandmatigIngesteld": false,
      "Url": null,
      "ExtraServices": "AED, EHBO, Gehandicaptentoilet, Bandenplaksetje te leen",
      "dia": null,
      "BerekentStallingskosten": true,
      "AantalReserveerbareKluizen": 0,
      "MaxStallingsduur": 0,
      "HeeftExterneBezettingsdata": false,
      "hasUniSectionPrices": false,
      "hasUniBikeTypePrices": false,
      "shadowBikeparkID": null,
      "BronBezettingsdata": "FMS",
      "reservationCostPerDay": "0",
      "wachtlijst_Id": null,
      "thirdPartyReservationsUrl": null
    },
    "sectiesTree": [
      {
        "externalId": "9933_007_1",
        "titel": "Caterplein",
        "omschrijving": null,
        "capaciteit": 869,
        "CapaciteitBromfiets": null,
        "kleur": "00FF00",
        "isKluis": false,
        "reserveringskostenPerDag": null,
        "urlwebservice": "",
        "Reservable": false,
        "NotaVerwijssysteem": "",
        "Bezetting": 76,
        "isactief": true,
        "qualificatie": "NONE",
        "sectieFietstypes": [
          {
            "BikeTypeID": 1
          },
          {
            "BikeTypeID": 2
          },
          {
            "BikeTypeID": 3
          },
          {
            "BikeTypeID": 4
          },
          {
            "BikeTypeID": 5
          },
          {
            "BikeTypeID": 6
          },
          {
            "BikeTypeID": 7
          },
          {
            "BikeTypeID": 8
          },
          {
            "BikeTypeID": 9
          },
          {
            "BikeTypeID": 10
          },
          {
            "BikeTypeID": 11
          },
          {
            "BikeTypeID": 12
          },
          {
            "BikeTypeID": 13
          }
        ],
        "kostenperioden": [
          {
            "index": 1,
            "tijdsspanne": "",
            "kosten": ""
          },
          {
            "index": 2,
            "tijdsspanne": "",
            "kosten": ""
          },
          {
            "index": 3,
            "tijdsspanne": "",
            "kosten": ""
          }
        ]
      }
    ],
    "tarievenTree": {
      "stalling": [],
      "sections": [
        {
          "externalId": "9933_007_1",
          "tariefregels": [],
          "bikeTypes": []
        }
      ]
    },
    "abonnementsvormenTree": [],
    "services": [
      {
        "ServiceID": "brommer"
      },
      {
        "ServiceID": "fietspomp"
      },
      {
        "ServiceID": "kluisjes"
      },
      {
        "ServiceID": "oplaadpunt"
      },
      {
        "ServiceID": "toilet"
      }
    ],
    "winkansen": [],
    "uitzonderingenopeningstijden": [
      {
        "openingDateTime": "2014-12-24T07:00:00.000Z",
        "closingDateTime": "2014-12-24T19:00:00.000Z"
      },
      {
        "openingDateTime": "2014-12-25T00:00:00.000Z",
        "closingDateTime": "2014-12-25T00:00:00.000Z"
      },
      {
        "openingDateTime": "2014-12-26T00:00:00.000Z",
        "closingDateTime": "2014-12-26T00:00:00.000Z"
      },
      {
        "openingDateTime": "2014-12-31T07:00:00.000Z",
        "closingDateTime": "2014-12-31T19:00:00.000Z"
      },
      {
        "openingDateTime": "2015-01-01T00:00:00.000Z",
        "closingDateTime": "2015-01-01T00:00:00.000Z"
      },
      {
        "openingDateTime": "2015-01-13T07:00:00.000Z",
        "closingDateTime": "2015-01-13T19:00:00.000Z"
      },
      {
        "openingDateTime": "2015-04-05T00:00:00.000Z",
        "closingDateTime": "2015-04-05T00:00:00.000Z"
      },
      {
        "openingDateTime": "2015-04-06T00:00:00.000Z",
        "closingDateTime": "2015-04-06T00:00:00.000Z"
      },
      {
        "openingDateTime": "2015-04-26T12:00:00.000Z",
        "closingDateTime": "2015-04-27T04:30:00.000Z"
      },
      {
        "openingDateTime": "2015-04-27T07:00:00.000Z",
        "closingDateTime": "2015-04-28T04:30:00.000Z"
      },
      {
        "openingDateTime": "2015-05-24T00:00:00.000Z",
        "closingDateTime": "2015-05-24T00:00:00.000Z"
      },
      {
        "openingDateTime": "2015-05-25T00:00:00.000Z",
        "closingDateTime": "2015-05-25T00:00:00.000Z"
      },
      {
        "openingDateTime": "2015-12-31T07:00:00.000Z",
        "closingDateTime": "2015-12-31T19:00:00.000Z"
      },
      {
        "openingDateTime": "2016-01-01T00:00:00.000Z",
        "closingDateTime": "2016-01-01T00:00:00.000Z"
      },
      {
        "openingDateTime": "2016-01-12T07:00:00.000Z",
        "closingDateTime": "2016-01-12T19:00:00.000Z"
      },
      {
        "openingDateTime": "2016-03-27T00:00:00.000Z",
        "closingDateTime": "2016-03-27T00:00:00.000Z"
      },
      {
        "openingDateTime": "2016-03-28T00:00:00.000Z",
        "closingDateTime": "2016-03-28T00:00:00.000Z"
      },
      {
        "openingDateTime": "2016-05-05T12:00:00.000Z",
        "closingDateTime": "2016-05-06T03:00:00.000Z"
      },
      {
        "openingDateTime": "2016-04-27T07:00:00.000Z",
        "closingDateTime": "2016-04-28T04:30:00.000Z"
      },
      {
        "openingDateTime": "2016-04-26T07:00:00.000Z",
        "closingDateTime": "2016-04-27T04:30:00.000Z"
      },
      {
        "openingDateTime": "2016-12-25T00:00:00.000Z",
        "closingDateTime": "2016-12-25T00:00:00.000Z"
      },
      {
        "openingDateTime": "2016-12-26T00:00:00.000Z",
        "closingDateTime": "2016-12-26T00:00:00.000Z"
      },
      {
        "openingDateTime": "2017-01-17T07:00:00.000Z",
        "closingDateTime": "2017-01-17T19:00:00.000Z"
      },
      {
        "openingDateTime": "2016-12-31T12:00:00.000Z",
        "closingDateTime": "2016-12-31T18:00:00.000Z"
      },
      {
        "openingDateTime": "2017-01-01T00:00:00.000Z",
        "closingDateTime": "2017-01-01T00:00:00.000Z"
      },
      {
        "openingDateTime": "2017-04-26T07:00:00.000Z",
        "closingDateTime": "2017-04-27T04:30:00.000Z"
      },
      {
        "openingDateTime": "2017-04-27T07:00:00.000Z",
        "closingDateTime": "2017-04-28T04:30:00.000Z"
      },
      {
        "openingDateTime": "2017-04-16T00:00:00.000Z",
        "closingDateTime": "2017-04-16T00:00:00.000Z"
      },
      {
        "openingDateTime": "2017-04-17T00:00:00.000Z",
        "closingDateTime": "2017-04-17T00:00:00.000Z"
      },
      {
        "openingDateTime": "2017-04-14T08:00:00.000Z",
        "closingDateTime": "2017-04-15T04:30:00.000Z"
      },
      {
        "openingDateTime": "2017-05-25T00:00:00.000Z",
        "closingDateTime": "2017-05-25T00:00:00.000Z"
      },
      {
        "openingDateTime": "2017-12-05T07:00:00.000Z",
        "closingDateTime": "2017-12-05T19:00:00.000Z"
      },
      {
        "openingDateTime": "2017-12-19T00:00:00.000Z",
        "closingDateTime": "2017-12-19T23:59:00.000Z"
      },
      {
        "openingDateTime": "2017-12-20T00:00:00.000Z",
        "closingDateTime": "2017-12-20T23:59:00.000Z"
      },
      {
        "openingDateTime": "2017-12-21T00:00:00.000Z",
        "closingDateTime": "2017-12-21T23:59:00.000Z"
      },
      {
        "openingDateTime": "2017-12-22T00:00:00.000Z",
        "closingDateTime": "2017-12-22T23:59:00.000Z"
      },
      {
        "openingDateTime": "2017-12-26T00:00:00.000Z",
        "closingDateTime": "2017-12-26T00:00:00.000Z"
      },
      {
        "openingDateTime": "2018-01-01T00:00:00.000Z",
        "closingDateTime": "2018-01-01T00:00:00.000Z"
      },
      {
        "openingDateTime": "2017-12-18T00:00:00.000Z",
        "closingDateTime": "2017-12-18T23:59:00.000Z"
      },
      {
        "openingDateTime": "2017-12-24T00:00:00.000Z",
        "closingDateTime": "2017-12-24T23:59:00.000Z"
      },
      {
        "openingDateTime": "2017-12-25T00:00:00.000Z",
        "closingDateTime": "2017-12-25T02:00:00.000Z"
      },
      {
        "openingDateTime": "2017-12-23T00:00:00.000Z",
        "closingDateTime": "2017-12-23T23:59:00.000Z"
      },
      {
        "openingDateTime": "2017-12-31T11:30:00.000Z",
        "closingDateTime": "2017-12-31T17:30:00.000Z"
      },
      {
        "openingDateTime": "2018-01-23T07:00:00.000Z",
        "closingDateTime": "2018-01-23T19:00:00.000Z"
      },
      {
        "openingDateTime": "2018-04-01T00:00:00.000Z",
        "closingDateTime": "2018-04-01T00:00:00.000Z"
      },
      {
        "openingDateTime": "2018-04-02T00:00:00.000Z",
        "closingDateTime": "2018-04-02T00:00:00.000Z"
      },
      {
        "openingDateTime": "2018-03-30T08:00:00.000Z",
        "closingDateTime": "2018-03-31T04:30:00.000Z"
      },
      {
        "openingDateTime": "2018-04-26T07:00:00.000Z",
        "closingDateTime": "2018-04-27T04:30:00.000Z"
      },
      {
        "openingDateTime": "2018-05-10T00:00:00.000Z",
        "closingDateTime": "2018-05-10T00:00:00.000Z"
      },
      {
        "openingDateTime": "2018-05-21T00:00:00.000Z",
        "closingDateTime": "2018-05-21T00:00:00.000Z"
      },
      {
        "openingDateTime": "2018-05-20T00:00:00.000Z",
        "closingDateTime": "2018-05-20T00:00:00.000Z"
      },
      {
        "openingDateTime": "2018-12-25T10:30:00.000Z",
        "closingDateTime": "2018-12-26T00:00:00.000Z"
      },
      {
        "openingDateTime": "2018-12-26T10:30:00.000Z",
        "closingDateTime": "2018-12-27T00:00:00.000Z"
      },
      {
        "openingDateTime": "2018-12-31T07:00:00.000Z",
        "closingDateTime": "2019-01-01T00:00:00.000Z"
      },
      {
        "openingDateTime": "2019-01-01T00:00:00.000Z",
        "closingDateTime": "2019-01-01T05:00:00.000Z"
      },
      {
        "openingDateTime": "2019-01-15T07:00:00.000Z",
        "closingDateTime": "2019-01-15T19:00:00.000Z"
      },
      {
        "openingDateTime": "2019-12-25T12:00:00.000Z",
        "closingDateTime": "2019-12-26T02:00:00.000Z"
      },
      {
        "openingDateTime": "2019-12-31T07:00:00.000Z",
        "closingDateTime": "2020-01-01T04:30:00.000Z"
      },
      {
        "openingDateTime": "2019-12-26T12:00:00.000Z",
        "closingDateTime": "2019-12-27T04:30:00.000Z"
      },
      {
        "openingDateTime": "2020-06-01T11:30:00.000Z",
        "closingDateTime": "2020-06-02T00:00:00.000Z"
      }
    ]
  }
};

export type StallingEntry = { stallingsId: string; title: string; coordsIndex: number };
export const STALLINGS: StallingEntry[] = [
  {
    "stallingsId": "9933_001",
    "title": "9933_001 - API Betaalde Stalling",
    "coordsIndex": 0
  },
  {
    "stallingsId": "9933_002",
    "title": "9933_002 - API Buurtstalling",
    "coordsIndex": 1
  },
  {
    "stallingsId": "9933_003",
    "title": "9933_003 - API Fietskluizen",
    "coordsIndex": 2
  },
  {
    "stallingsId": "9933_004",
    "title": "9933_004 - API Geautomatiseerde Stalling",
    "coordsIndex": 3
  },
  {
    "stallingsId": "9933_005",
    "title": "9933_005 - API Onbewaakte Stalling",
    "coordsIndex": 4
  },
  {
    "stallingsId": "9933_006",
    "title": "9933_006 - API Fietstrommel",
    "coordsIndex": 5
  },
  {
    "stallingsId": "9933_007",
    "title": "9933_007 - API Toezicht",
    "coordsIndex": 6
  }
];

export const STALLINGS_COUNT = 7;
