name: Deploy to Digital Ocean

on:
  workflow_dispatch:
  push:
    branches:
      - veiligstallen-v2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DROPLET_HOST }}
          username: ${{ vars.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/veiligstallen
            git pull origin veiligstallen-v2

            # Create docker-compose.yml if it doesn't exist
            cat > docker-compose.yml << 'EOL'
            version: "3"

            services:
              app:
                build:
                  context: .
                  args:
                    NEXT_PUBLIC_API_BASE_URL: ${{ vars.NEXT_PUBLIC_API_BASE_URL }}
                    NEXT_PUBLIC_WEB_BASE_URL: ${{ vars.NEXT_PUBLIC_WEB_BASE_URL }}
                    DATABASE_URL: ${{ secrets.DATABASE_URL }}
                    NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
                    NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
                    NEXT_PUBLIC_MAPBOX_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPBOX_TOKEN }}
                    LOGINTOKEN_SIGNER_PRIVATE_KEY: ${{ secrets.LOGINTOKEN_SIGNER_PRIVATE_KEY }}
                restart: always
                ports:
                  - "3000:3000"
                environment:
                  - NODE_ENV=production
                extra_hosts:
                  - "host.docker.internal:host-gateway"
                network_mode: "host"
            EOL

            # Create .env file for build
            cat > .env << EOL
            NEXT_PUBLIC_API_BASE_URL=${{ vars.NEXT_PUBLIC_API_BASE_URL }}
            NEXT_PUBLIC_WEB_BASE_URL=${{ vars.NEXT_PUBLIC_WEB_BASE_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL=${{ vars.NEXTAUTH_URL }}
            NEXT_PUBLIC_MAPBOX_TOKEN=${{ secrets.NEXT_PUBLIC_MAPBOX_TOKEN }}
            LOGINTOKEN_SIGNER_PRIVATE_KEY=${{ secrets.LOGINTOKEN_SIGNER_PRIVATE_KEY }}
            EOL

            docker-compose build
            docker-compose down
            docker-compose up -d
