name: Deploy to Digital Ocean

on:
  push:
    branches:
      - veiligstallen-v2
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/veiligstallen
            git pull origin veiligstallen-v2

            # Create docker-compose.yml if it doesn't exist
            cat > docker-compose.yml << 'EOL'
            version: "3"

            services:
              app:
                build: .
                restart: always
                ports:
                  - "3000:3000"
                environment:
                  - NODE_ENV=production
                env_file:
                  - .env
                network_mode: "host"
            EOL

            docker-compose build
            docker-compose down
            docker-compose up -d
