import React, { useState, useEffect, useRef } from "react";
import { type ReportBikepark, type ReportType, getAvailableReports } from "../reports/ReportsFilter";
import { type AvailableDataDetailedResult } from "~/backend/services/reports/availableData";
import ExportSectionReport from "./ExportSectionReport";
import ExportSectionRawData from "./ExportSectionRawData";

export type MonthData = {
  year: number;
  month: number;
}

export type BikeparkData = {
  bikeparkID: string;
  bikeparkTitle: string;
  monthsWithData: MonthData[];
}

export interface ReportComponentProps {
  gemeenteID: string | undefined;
  gemeenteName: string | undefined;
  firstDate: Date;
  lastDate: Date;
  bikeparks: ReportBikepark[];
}

export const buttonbase = "px-2 py-1 bg-white border border-gray-300 rounded hover:bg-gray-200 transition-colors duration-150 text-xs font-medium text-gray-700 flex items-center ml-1 disabled:opacity-60 disabled:cursor-wait disabled:hover:bg-white";
export const libase="text-base font-medium text-gray-800 mb-2 flex flex-row"

export const csvDownloadKey = (stallingsID: string | undefined, jaar: number, maand?: number): string =>
  [stallingsID ?? "alle", String(jaar), maand === undefined ? "" : String(maand)].join("|");

export const CsvDownloadSpinner: React.FC = () => (
  <span
    className="inline-block h-3 w-3 border-2 border-gray-500 border-t-transparent rounded-full animate-spin mr-1"
    aria-hidden="true"
  />
);

export type CsvExportType = "transacties" | "ruwedata" | "stallingsduur" | "bezetting";

export type CsvExportRequest = {
  exportType: CsvExportType;
  gemeenteID: string;
  stallingsID?: string;
  jaar: number;
  maand?: number;
};

const filenameFromContentDisposition = (header: string | null): string | undefined => {
  const match = header?.match(/filename="?([^"]+)"?/);
  return match?.[1];
};

/**
 * Downloads a CSV report from the Next.js export API. These reports used to be
 * pre-generated by ColdFusion and served from static.veiligstallen.nl.
 */
export const downloadCsvExport = async (request: CsvExportRequest): Promise<void> => {
  const { exportType, gemeenteID, stallingsID, jaar, maand } = request;

  const query = new URLSearchParams({ gemeenteID, jaar: String(jaar) });
  if (stallingsID) query.set("stallingsID", stallingsID);
  if (maand !== undefined) query.set("maand", String(maand));

  const response = await fetch(`/api/protected/export/${exportType}?${query.toString()}`);
  if (!response.ok) {
    const message = await response
      .json()
      .then((body: { error?: string }) => body.error)
      .catch(() => undefined);
    throw new Error(message || `Download mislukt (${response.status})`);
  }

  const blob = await response.blob();
  const url = URL.createObjectURL(blob);
  try {
    const link = document.createElement("a");
    link.href = url;
    link.download =
      filenameFromContentDisposition(response.headers.get("Content-Disposition")) ??
      `${jaar}_${exportType}.csv`;
    document.body.appendChild(link);
    link.click();
    link.remove();
  } finally {
    URL.revokeObjectURL(url);
  }
};

export const convertToBikeparkData = (bikeparks: ReportBikepark[], data: AvailableDataDetailedResult[]): BikeparkData[] => {
  // change this to map/reduce
  const bikeparkData: BikeparkData[] = [];
  data.forEach(d => {
      const [yearstr, monthstr]  = d.yearmonth.split("-");
      if(!yearstr || !monthstr) {
          console.error("ExportComponent: no year or month: ", d);
          return;
      }

      const year = parseInt(yearstr);
      const month = parseInt(monthstr);

      let bikepark = bikeparkData.find(bp => bp.bikeparkID === d.locationID);
      if(!bikepark) {
          const info = bikeparks.find(bp => bp.StallingsID === d.locationID);
          bikepark = {
              bikeparkID: d.locationID, 
              bikeparkTitle: info?.Title || "unknown",
              monthsWithData: []
          }
          bikeparkData.push(bikepark);
      }
      
      if(bikepark && year && month) {
          if(!bikepark.monthsWithData.find(md => md.year === year && md.month === month)) { 
              bikepark.monthsWithData.push({year, month});
          }
      }
  });

  return bikeparkData;
}


const ExportLoadingSpinner: React.FC = () => (
  <div className="spinner" style={{ margin: "auto" }}>
    <div className="loader"></div>
  </div>
);

const ExportComponent: React.FC<ReportComponentProps> = ({
  gemeenteID,
  gemeenteName,
  firstDate,
  lastDate,
  bikeparks,
}) => {
  const [reportType, setReportType] = useState<ReportType>("transacties_voltooid");
  const [bikeparkData, setBikeparkData] = useState<BikeparkData[]>([]);
  const [loading, setLoading] = useState(true);
  const [errorState, setErrorState] = useState("");

  const validBikeparkIDs = bikeparks.map(bp => bp.StallingsID).filter(bp => bp !== "" && bp !== undefined && bp !== null);
  const bikeparkIDsKey = validBikeparkIDs.join(",");
  const startDT = firstDate.getTime();
  const endDT = lastDate.getTime();
  const fetchKey = ["transacties_voltooid", bikeparkIDsKey, String(startDT), String(endDT)].join("|");
  const loadedFetchKeyRef = useRef<string | null>(null);

  useEffect(() => {
    const fetchReportData = async () => {
      const showLoadingUI = loadedFetchKeyRef.current !== fetchKey;
      if (showLoadingUI) {
        setLoading(true);
      }

      if (validBikeparkIDs.length !== bikeparks.length) {
        console.warn("ExportComponent: some bikeparks have no StallingsID. These are not shown.");
      }

      try {
        const response = await fetch("/api/protected/database/availableDataDetailed", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            reportType: "transacties_voltooid",
            bikeparkIDs: validBikeparkIDs,
            startDT: firstDate,
            endDT: lastDate,
          }),
        });

        if (!response.ok) {
          throw new Error(`Error: ${response.statusText}`);
        }

        const data = await response.json() as AvailableDataDetailedResult[] | false;
        if (data) {
          setBikeparkData(convertToBikeparkData(bikeparks, data));
          setErrorState("");
          loadedFetchKeyRef.current = fetchKey;
        } else {
          setErrorState("Unable to fetch report data");
        }
      } catch (error) {
        console.error(error);
        setErrorState("Unable to fetch report data");
      } finally {
        if (showLoadingUI) {
          setLoading(false);
        }
      }
    };

    fetchReportData();
  }, [bikeparkIDsKey, startDT, endDT, fetchKey]);

  const renderReportTypeSelect = () => {
    // "Absolute bezetting" has no CSV export of its own; the bezetting export
    // already contains both the absolute and the procentuele columns.
    const availableReports = getAvailableReports(false).filter(
      (report) => report.id !== "absolute_bezetting"
    );
    return (
      <div className="form-group row flex flex-row">
        <label htmlFor="report" className="col-xs-3 col-sm-2 col-form-label font-bold mr-5">Export</label>
        <div className="col-sm-10 col-md-6 border-2 border-gray-300 rounded-md">
          <select
            className="form-control"
            name="report"
            id="report"
            value={reportType}
            onChange={(e) => setReportType(e.target.value as ReportType)}
            required
          > {availableReports.map((report) => (
            <option key={report.id} value={report.id}>{report.title}</option>
          ))}
          </select>
        </div>
      </div>
    )
  }

  if(undefined === gemeenteID || gemeenteID === "") {
    return <div className="text-center text-gray-500 mt-10 text-xl" >Selecteer een gemeente om rapportages te bekijken</div>;
  }

  return (
      <div className="noPrint w-full" id="ExportComponent">
        <div className="flex flex-col space-y-4 p-4">
          {renderReportTypeSelect()}

          <div className="max-w-7xl">
            {loading ? (
              <ExportLoadingSpinner />
            ) : errorState ? (
              <div style={{ color: "red", fontWeight: "bold" }}>{errorState}</div>
            ) : (
              <>
                <ExportSectionReport
                  reportType={reportType}
                  bikeparks={bikeparks}
                  gemeenteID={gemeenteID}
                  gemeenteName={gemeenteName || ""}
                  firstDate={firstDate}
                  lastDate={lastDate}
                  bikeparkData={bikeparkData}
                />
                <ExportSectionRawData
                  bikeparks={bikeparks}
                  gemeenteID={gemeenteID}
                  gemeenteName={gemeenteName || ""}
                  firstDate={firstDate}
                  lastDate={lastDate}
                  bikeparkData={bikeparkData}
                />
              </>
            )}
          </div>
      </div>
    </div>
  );
};

export default ExportComponent;
